### PR TITLE
Add oemof model for VDI

### PR DESCRIPTION
**Pull request by robmip**
The whole stemp abw was erased as I will concentrate first on the oemof model

### CODE REVIEW

**Comment by robmip** [comment]
@c-moeller : here is the first model approach. With the structure from the example and the components created with @oakca

**Comment by Bachibouzouk** [comment]
@robmip - a good thing to add in the REAMDE would be the command line one should run to use your code as well as the minimum requirements for the program to run

**Comment by oakca** [comment]
Let's make it in following way @Bachibouzouk @robmip :

After you create a functioning model, you can commit it in the rl-institut/peak_shaving_app repo, where you have a right of writing/deleting/updating so that you dont need to create pull request for every commit. 

You can also change the readme file there. I think it makes more sense.

~Btw @Bachibouzouk are you also commiting for this app? If yes I need to give you also writing rights.~ done.

First version you can commit directly into master, then I show you guys how to name branches etc. So that we can keep the rl-institut syntax.

I think it makes more sense to have a clean repo, it would make things also easier for people who may later use this app.

And finally if this repo is just a copy of another repo we can remove it to prevent complications.

**Comment by Bachibouzouk** [comment]
> Let's make it in following way @Bachibouzouk @robmip :
> 
> After you create a functioning model, you can commit it in the rl-institut/peak_shaving_app repo, where you have a right of writing/deleting/updating 

@oakca - Why create another repository for the app? Is this one not ok for that?

> so that you dont need to create pull request for every commit.

If I didn tell @robmip to create a PR we wouldn't be able to have this conversation right now ;) (we would have it in private and there wouldn't be a trace of it for other collaborators). 
> 
> You can also change the readme file there. I think it makes more sense.
> 
> Btw @Bachibouzouk are you also commiting for this app? If yes I need to give you also writing rights.
@c-moeller gave me the rights already ;)

> First version you can commit directly into master, then I show you guys how to name branches etc. So that we can keep the rl-institut syntax.

you mean https://nvie.com/posts/a-successful-git-branching-model/ ? Otherwise can you send me a link to the relevant rli docu? Thanks :)

> I think it makes more sense to have a clean repo, it would make things also easier for people who may later use this app.

I was planning to do a rebase to clean the history of the repository

**Comment by oakca** [comment]
@Bachibouzouk I though he had no rights of writing in this repo that is why I created a new one and gave him the rights. (because of the pull request I though this)

About branching it was exactly the thing I wanted to show :)

Lastly, I dont really know if it says in the link but branch naming is basically:

master - where you have the stable versions
dev - where you develop
feature/name_of_the_feature - where you develop features of the code

then you merge from down to up

e.g.: you commit something in feature/... , it is done, you merge into dev and delete feature/... branch. 

then you develop more in dev. finally you decide okay now I implemented too many things so lets do a version 2, so you merge dev into master, but this time you keep dev for new developments

**Comment by Bachibouzouk** [comment]
@robmip - can you strip down your `requirements.txt` file so that it contains the strictly necessary dependencies to run your oemof code ? We'll add the relevant one when integrating into WAM later :)

**Comment by oakca** [comment]
I am guess you are keeping this one so, I am removing the other repo. Sorry for complication. I just though "oh he cannot merge it" since this one stays not merged for some days. Have a nice day you both :)^^

**Pull request closed without merging**
